use_format_specific_options: false
default_highlighting: GESHIFILTER_DEFAULT_DONOTHING
default_line_numbering: 0
use_highlight_string_for_php: false
enable_keyword_urls: true
decode_entities: false
css_mode: 1
code_container: '2'
tags: 'code blockcode'
tag_styles:
  1: 1
  2: 2
  4: 0
  8: 0
  16: 0
tab_width: 8
language:
  php:
    enabled: true
    tags: php
  cpp:
    enabled: true
    tags: cpp
  java:
    enabled: true
    tags: java
_core:
  default_config_hash: 1jZtSc2CSiEBA45nbX0wMKFY3bmcilIwOBQCKFscK0U
